"""Update student_lessons

Revision ID: 21f33de9befc
Revises: 3766f9faed2c
Create Date: 2022-04-01 01:15:13.174711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f33de9befc'
down_revision = '3766f9faed2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessonstudent', sa.Column('completed', sa.Boolean(), nullable=True))
    op.drop_column('lessonstudent', 'is_unlocked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessonstudent', sa.Column('is_unlocked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('lessonstudent', 'completed')
    # ### end Alembic commands ###
