"""Add content to lesson

Revision ID: 27429eff2756
Revises: 939c248d42e9
Create Date: 2022-03-22 20:02:53.824541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27429eff2756'
down_revision = '939c248d42e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('content', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'content')
    # ### end Alembic commands ###
