"""rename due

Revision ID: 3766f9faed2c
Revises: cb44cc03fce7
Create Date: 2022-03-29 15:02:51.540845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3766f9faed2c'
down_revision = 'cb44cc03fce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessonstudent', sa.Column('due', sa.DateTime(), nullable=True))
    op.drop_column('lessonstudent', 'due_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessonstudent', sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('lessonstudent', 'due')
    # ### end Alembic commands ###
