"""Change password column names

Revision ID: 6caaa3d7a116
Revises: 04e664bc9438
Create Date: 2022-01-24 19:34:32.299912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6caaa3d7a116'
down_revision = '04e664bc9438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('staff', 'password')
    op.add_column('student', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('student', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('student', 'hashed_password')
    op.add_column('staff', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('staff', 'hashed_password')
    # ### end Alembic commands ###
