"""Add message

Revision ID: b2b0ca940f20
Revises: 6caaa3d7a116
Create Date: 2022-02-22 17:45:42.514084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b0ca940f20'
down_revision = '6caaa3d7a116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('to_student_id', sa.Integer(), nullable=True),
    sa.Column('from_student_id', sa.Integer(), nullable=True),
    sa.Column('to_staff_id', sa.Integer(), nullable=True),
    sa.Column('from_staff_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
