"""Update

Revision ID: cb44cc03fce7
Revises: 27429eff2756
Create Date: 2022-03-22 20:42:10.851561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb44cc03fce7'
down_revision = '27429eff2756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
